apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer
  selector:
    app: notification-service # This should match the Deployment labels
  ports:
  - port: 8000
    targetPort: 8000
