apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog-service # This should match the Deployment labels
  ports:
  - port: 3000
    targetPort: 3000
