apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth # This should match the Deployment labels
  ports:
  - port: 8888
    targetPort: 8888
