apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service # Ensure this matches the labels in the Pod template metadata
  template:
    metadata:
      labels:
        app: payment-service # This must match the selector.matchLabels
    spec:
      containers:
      - name: payment-service-app
        image: australia-southeast1-docker.pkg.dev/sit737-24t1-subhash-c10ae83/auth-repo/payment-service:v5.0
        ports:
        - containerPort: 6000
        env:
          - name: PORT
            value: "6000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"