apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  selector:
    app: payment-service # This should match the Deployment labels
  ports:
  - port: 6000
    targetPort: 6000
