apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  type: LoadBalancer
  selector:
    app: booking-service # This should match the Deployment labels
  ports:
  - port: 4000
    targetPort: 4000
