name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'api-gateway/**'
      - 'catalog-service/**'
      - 'booking-service/**'
      - 'payment-service/**'
      - 'notification-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, api-gateway, catalog-service, booking-service, payment-service, notification-service]
        region: [australia-southeast1]
        project-id: [sit737-24t1-subhash-c10ae83]
        repo: [auth-repo]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install

      - name: Build Docker image
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ matrix.service }} .

      - name: Tag Docker image
        run: |
          docker tag ${{ matrix.service }} ${{ matrix.region }}-docker.pkg.dev/${{ matrix.project-id }}/${{ matrix.repo }}/${{ matrix.service }}:${{ github.sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Debug Authentication
        run: |
          echo "GCP Service Account Key: ${{ secrets.GCP_SA_KEY }}"
          gcloud auth list
          gcloud config list

      - name: Configure Docker to use gcloud as a credential helper
        timeout-minutes: 5
        run: |
          gcloud auth configure-docker ${{ matrix.region }}-docker.pkg.dev || echo "Failed to configure Docker"

      - name: Debug Docker Configuration
        if: ${{ failure() }}
        run: |
          docker info
          cat ~/.docker/config.json

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push ${{ matrix.region }}-docker.pkg.dev/${{ matrix.project-id }}/${{ matrix.repo }}/${{ matrix.service }}:${{ github.sha }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ matrix.project-id }}

      - name: Verify Google Cloud SDK installation
        run: |
          gcloud --version
          gcloud components list

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Debug Kubernetes Cluster
        run: |
          gcloud container clusters get-credentials cinema-cluster --region ${{ matrix.region }} --project ${{ matrix.project-id }}
          kubectl cluster-info

      - name: Deploy to GKE
        run: |
          # Delete existing pods
          kubectl delete pods -l app=${{ matrix.service }} --force --grace-period=0 --ignore-not-found=true

          kubectl apply -f ${{ matrix.service }}/${{ matrix.service }}-service.yaml
          kubectl apply -f ${{ matrix.service }}/${{ matrix.service }}-deployment.yaml

          # Set the new image for the deployment
          kubectl set image deployment/${{ matrix.service }} ${{ matrix.service }}-app=${{ matrix.region }}-docker.pkg.dev/${{ matrix.project-id }}/${{ matrix.repo }}/${{ matrix.service }}:${{ github.sha }}
